sudo: false
# MANUAL_UPDATE: Update to the latest Ubuntu dist.
dist: trusty
language: node_js
node_js:
  # MANUAL_UPDATE: Update to the latest node version.
  - "7.7.2"
  - "node"

branches:
  only:
    - master

script:
  - npm run build.prod
  - ng lint
  - npm run server.lint

notifications:
  email:
    on_failure: change
    on_success: change