sudo: false
# MANUAL_UPDATE: Update to the latest Ubuntu dist.
dist: trusty
language: node_js
node_js:
  # MANUAL_UPDATE: Update to the latest node version.
  - "7.7.2"
  - "node"

cache:
  directories:
    - node_modules

before_script:
  # Set an empty Firebase client config file as the config file is not checked in
  # this repository.
  - cp src/firebase.config.ts.stub src/firebase.config.ts

script:
  - npm run build.prod
  - ./node_modules/.bin/tsc
  - npm run lint

notifications:
  email:
    on_failure: change
    on_success: change
